--- 
abstract: vCard view for Catalyst
author: Brian Cassidy <bricas@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-View-vCard
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 0
  Text::vCard: 0
version: 0.02
